# Generated by Django 3.2.8 on 2022-08-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Organizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_contable', models.CharField(max_length=4)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
                ('unidad_organizativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unidad_organizativa')),
            ],
        ),
    ]
