# Generated by Django 3.2.8 on 2022-08-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220812_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo_al_presupuesto',
            old_name='cueta',
            new_name='cuenta',
        ),
    ]
