# Generated by Django 3.2.8 on 2022-08-05 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_solicitud_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='nombre',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
