# Generated by Django 3.2.8 on 2022-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220907_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='telf',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
