# Generated by Django 3.2.8 on 2022-08-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220817_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoriza',
            name='cargo',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoriza',
            name='dependencia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
