# Generated by Django 3.2.8 on 2022-08-06 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220805_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_destino', to='app.municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='regreso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_regreso', to='app.municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_origen', to='app.municipio'),
        ),
    ]
