# Generated by Django 3.2.8 on 2022-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_cueta_cargo_al_presupuesto_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='autoriza',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='cargo_presupuesto',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='parleg',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
