# Generated by Django 3.2.8 on 2022-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220825_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitante',
            old_name='permiso',
            new_name='cargo',
        ),
        migrations.AddField(
            model_name='modelo',
            name='area_trabajo_solicita',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='cargo_autoriza',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='cargo_solicita',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelo',
            name='dependencia_autoriza',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
