# Generated by Django 3.2.8 on 2022-09-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_solicitante_telf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
