# Generated by Django 3.2.8 on 2022-08-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220806_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
