# Generated by Django 3.2.8 on 2022-09-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220909_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parleg',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trabajador'),
        ),
    ]
