# Generated by Django 3.2.9 on 2022-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_parleg_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='parleg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(max_length=200),
        ),
    ]
