# Generated by Django 3.2.8 on 2022-08-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220815_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='observaciones',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
