# Generated by Django 3.2.8 on 2022-08-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220807_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.provincia'),
            preserve_default=False,
        ),
    ]
