# Generated by Django 3.2.8 on 2022-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220830_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='c_contable',
            field=models.CharField(max_length=4),
        ),
    ]
