# Generated by Django 3.2.8 on 2022-08-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220815_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoriza',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='autoriza',
            name='unidad_organizativa',
        ),
        migrations.AddField(
            model_name='solicitante',
            name='permiso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='unidad_organizativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.unidad_organizativa'),
            preserve_default=False,
        ),
    ]
