# Generated by Django 3.2.12 on 2023-01-04 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220910_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 1, 4)),
        ),
    ]
