# Generated by Django 3.2.8 on 2022-08-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_solicitud_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='user',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='nombre_y_apellidos',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
