# Generated by Django 3.2.8 on 2022-08-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_solicitud_c_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='c_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.c_contable'),
        ),
    ]
