# Generated by Django 3.2.8 on 2022-08-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_solicitud_c_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='parleg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trabajador_parleg', to='app.trabajador'),
        ),
    ]
