# Generated by Django 3.2.8 on 2022-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220807_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
