# Generated by Django 3.2.8 on 2022-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_solicitud_parleg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='parleg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
