# Generated by Django 3.2.8 on 2022-08-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220830_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='origen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='provincia',
            field=models.CharField(max_length=50),
        ),
    ]
