# Generated by Django 3.2.8 on 2022-08-10 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_alter_solicitud_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcualificado',
            name='permiso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalcualificado',
            name='unidad_organizativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.unidad_organizativa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalcualificado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
