# Generated by Django 3.2.8 on 2022-08-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220810_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consec', models.IntegerField(auto_created=True)),
                ('solicitudes', models.ManyToManyField(to='app.Solicitud')),
            ],
        ),
    ]
