# Generated by Django 3.2.8 on 2022-09-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220831_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_origen', to='app.municipio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provincia'),
        ),
    ]
