# Generated by Django 3.2.8 on 2022-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='consec',
            field=models.IntegerField(),
        ),
    ]
