# Generated by Django 3.2.8 on 2022-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220902_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='regreso',
            field=models.CharField(max_length=50),
        ),
    ]
