# Generated by Django 3.2.8 on 2022-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_solicitud_regreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='prov_destino',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
