# Generated by Django 3.2.8 on 2022-08-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_nombre_modelo_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='creador',
        ),
    ]
