# Generated by Django 3.2.8 on 2022-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_modelo_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
