# Generated by Django 3.2.8 on 2022-08-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_nombre_modelo_creador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='creador',
            new_name='nombre',
        ),
    ]
